[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
continuous_token = "9KwgDXHGibr8yaGGMLPSvE6y7Yxfbkd8Rv4K7AkmCTgn"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json --grep \"@local\" -t 1000000 \"tests/**/*.ts\""
test = "yarn run ts-mocha -p ./tsconfig.json --grep \"@devnet\" -t 1000000 \"tests/**/*.ts\""

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
program = "tests/spl_tokn_2022_program.so"